rethinkdb:
  restart: always
  image: rethinkdb

api:
  image: iojs
  command: npm start
  env_file: ./env/api.env
  environment:
    - NODE_ENV=development
    - HOSTNAME=0.0.0.0
    - RETHINKDB_HOST=rethinkdb
    - RETHINKDB_PORT=28015
    - RETHINKDB_DB=test
    - NPM_CONFIG_LOGLEVEL=http
    - CLI_ENABLED=true
    - CLI_PORT=4000
  working_dir: /app
  volumes:
    - ./api:/app
  links:
    - rethinkdb
  expose:
    - 3000
  ports:
    - 4000

apiproxy:
  restart: always
  image: tutum/haproxy
  environment:
    - BACKEND_PORT=3000
  links:
    - api

nginx:
  restart: always
  image: lewg/nginx-pagespeed
  volumes:
    - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./config/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
    - ./config/nginx/credentials:/etc/nginx/credentials:ro
    - ./config/nginx/ssl:/etc/nginx/ssl:ro
  links:
    - rethinkdb
    - apiproxy
  ports:
    - 80:80
    - 443:443
