rethinkdb:
  image: rethinkdb
  environment:
    - VIRTUAL_HOST=rethinkdb.fou.local
    - VIRTUAL_PORT=8080
  ports:
    - 28015:28015

redis:
  image: redis
  ports:
    - 6379:6379

api:
  image: iojs
  command: npm start
  environment:
    - NODE_ENV=development
    - NPM_CONFIG_LOGLEVEL=http
    - API_PORT=5000
    - API_HOSTNAME=0.0.0.0
    - RETHINKDB_HOST=rethinkdb
    - RETHINKDB_PORT=28015
    - RETHINKDB_DB=dev
    - API_CLI_ENABLED=true
    - API_CLI_PORT=4000
    - API_CLI_USER=admin
    - API_CLI_PASS=admin
    - VIRTUAL_HOST=api.fou.local
    - VIRTUAL_PORT=5000
  working_dir: /app
  volumes:
    - ./api:/app
  links:
    - rethinkdb
  ports:
    - 4000:4000
    - 5000:5000

frontend:
  image: iojs
  command: npm start
  environment:
    - NODE_ENV=development
    - NPM_CONFIG_LOGLEVEL=http
    - FRONTEND_PORT=9090
    - FRONTEND_HOSTNAME=0.0.0.0
    - FRONTEND_API_URI=http://api:5000
    - FRONTEND_API_TOKEN=123
    - FRONTEND_SESSION_KEYS=1337,007,abc
    - FRONTEND_REDIS_HOST=redis
    - FRONTEND_REDIS_PORT=6379
    - VIRTUAL_HOST=fou.local
    - VIRTUAL_PORT=9090
  working_dir: /app
  volumes:
    - ./frontend:/app
  links:
    - api
    - redis
  ports:
    - 9090:9090

nginx:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  links:
    - api
    - frontend
  ports:
    - 80:80
