rethinkdb:
  image: rethinkdb
  environment:
    - VIRTUAL_HOST=rethinkdb.fou.local
    - VIRTUAL_PORT=8080
  ports:
    - 28015:28015

api:
  image: iojs
  command: npm start
  environment:
    - NODE_ENV=development
    - PORT=3000
    - HOSTNAME=0.0.0.0
    - RETHINKDB_HOST=rethinkdb
    - RETHINKDB_PORT=28015
    - RETHINKDB_DB=test
    - NPM_CONFIG_LOGLEVEL=http
    - CLI_ENABLED=true
    - CLI_PORT=4000
    - VIRTUAL_HOST=api.fou.local
    - VIRTUAL_PORT=3000
  working_dir: /app
  volumes:
    - ./api:/app
  links:
    - rethinkdb
  ports:
    - 4000:4000

nginx:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - 80:80
