redis:
  restart: on-failure:3
  image: redis

redmon:
  restart: on-failure:3
  image: vieux/redmon
  links:
    - redis
  command: -r redis://redis:6379

rethinkdb:
  restart: on-failure:3
  image: rethinkdb

api:
  restart: on-failure:3
  image: iojs
  volumes:
    - ./api/:/app/
  working_dir: /app/
  env_file: ./env/api_secret.env
  command: npm start
  links:
    - redis
    - rethinkdb
  expose:
    - "3000"

nginx:
  restart: on-failure:3
  image: nginx
  volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
  links:
    - api
    - redis
    - redmon
    - rethinkdb
  ports:
    - "80:80"
