api:
  restart: on-failure:3
  image: iojs
  volumes:
    - ./api/:/app/
  working_dir: /app/
  command: npm start
  expose:
    - "3000"
nginx:
  restart: on-failure:3
  image: nginx
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  links:
    - api
  ports:
    - "80:80"
