rethinkdb:
  image: rethinkdb
  environment:
    - VIRTUAL_HOST=rethinkdb.fou.local
    - VIRTUAL_PORT=8080
  ports:
    - 28015:28015

redis:
  image: redis
  ports:
    - 6379:6379

api:
  image: iojs
  command: npm start
  environment:
    - NODE_ENV=development
    - HOSTNAME=0.0.0.0
    - RETHINKDB_HOST=rethinkdb
    - RETHINKDB_PORT=28015
    - RETHINKDB_DB=dev
    - NPM_CONFIG_LOGLEVEL=http
    - CLI_ENABLED=true
    - CLI_PORT=4000
    - VIRTUAL_HOST=api.fou.local
    - VIRTUAL_PORT=8080
  working_dir: /app
  volumes:
    - ./api:/app
  links:
    - rethinkdb
  ports:
    - 4000:4000
    - 5000:5000

frontend:
  image: iojs
  command: npm start
  environment:
    - NODE_ENV=development
    - PORT=5000
    - NPM_CONFIG_LOGLEVEL=http
    - VIRTUAL_HOST=fou.local
    - VIRTUAL_PORT=5000
  working_dir: /app
  volumes:
    - ./frontend:/app
  links:
    - api
  ports:
    - 5000:5000

nginx:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  links:
    - api
    - frontend
  ports:
    - 80:80
