rethinkdb:
  restart: on-failure:3
  image: rethinkdb

api:
  restart: on-failure:3
  image: iojs
  volumes:
    - ./api/:/app/
  working_dir: /app/
  env_file: ./env/api_secret.env
  command: npm start
  links:
    - rethinkdb
  expose:
    - "3000"

nginx:
  restart: on-failure:3
  image: nginx
  volumes:
    - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  links:
    - api
    - rethinkdb
  ports:
    - "80:80"
