rethinkdb:
  restart: always
  image: rethinkdb

api:
  image: iojs
  command: npm start
  env_file: ./env/api.env
  environment:
    - HOSTNAME=0.0.0.0
    - RETHINKDB_HOST=rethinkdb
    - RETHINKDB_PORT=28015
    - RETHINKDB_DB=test
  working_dir: /app
  volumes:
    - ./api:/app
  links:
    - rethinkdb
  expose:
    - 3000

apiproxy:
  restart: always
  image: tutum/haproxy
  environment:
    - BACKEND_PORT=3000
  links:
    - api

nginx:
  restart: always
  image: lewg/nginx-pagespeed
  volumes:
    - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./config/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
  links:
    - rethinkdb
    - apiproxy
  ports:
    - 80:80
